@startuml

actor Usuario
participant "PantallaVerificacion/Escaneo" as GUI
participant "ArchivoDAO" as DAO
participant "Conexion" as DB

Usuario -> GUI : agregarArchivo()
activate GUI

GUI -> DAO : insertarArchivo(archivo)
activate DAO

DAO -> DB : getConnection()
activate DB
DB --> DAO : connection
deactivate DB

DAO -> DB : prepareStatement(sql)
activate DB
DB --> DAO : pstmt
deactivate DB

DAO -> DB : executeUpdate()
DB --> DAO : result
deactivate DAO

DAO --> GUI : result
deactivate GUI

@enduml

